language: php
php:
  - 7.3
sudo: enabled
dist: xenial
addons:
  hosts:
    - sspanel.test
before_install:
  - sudo apt-get -qq install -y nodejs php7.3-fpm php7.3-curl php7.3-gd php7.3-mbstring php7.3-xml php7.3-xmlrpc php7.3-opcache php7.3-zip php7.3-json php7.3-bz2 php7.3-bcmath nginx dash bash curl

  - sudo cat /etc/nginx/nginx.conf
  - sudo ls /etc/nginx/sites-enabled/
  - sudo ls /etc/nginx/sites-available/
  - sudo cp test/travis-ci-nginx.conf /etc/nginx/sites-available/mrp.test.conf
  - sudo rm -rf /etc/nginx/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR?g" --in-place /etc/nginx/sites-available/mrp.test.conf
  - sudo ln -s /etc/nginx/sites-available/mrp.test.conf /etc/nginx/sites-enabled/
  - sudo ls /etc/nginx/sites-enabled/
  - sudo ls /etc/nginx/sites-available/
  - sudo cat /etc/nginx/sites-enabled/mrp.test.conf
install:
  # Make composer download 10x faseter
  # - composer global require hirak/prestissimo
  - composer install

script:
  - sudo chmod -R 755 *
  - arrcookie=($(php xcat getCookie 1 | sed 's| |\n|g'))
  - sudo service php7.3-fpm restart
  - sudo nginx -c /etc/nginx/nginx.conf
  - sudo chmod -R 777 $TRAVIS_BUILD_DIR
  - sudo chown -R www-data:www-data $TRAVIS_BUILD_DIR

cache:
  directories:
    - uim-index-dev/node_modules
    - $HOME/.composer/cache/files
