language: php

php:
  - 7.2

sudo: enabled

before_install:
  - sudo apt-get install -y nginx dash bash curl
  - sudo cat /etc/nginx/nginx.conf
  - sudo ls /etc/nginx/sites-enabled/
  - sudo ls /etc/nginx/sites-available/
  - sudo cp travis-ci-nginx.conf /etc/nginx/sites-available/mrp.test.conf
  - sudo rm -rf /etc/nginx/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR?g" --in-place /etc/nginx/sites-available/mrp.test.conf
  - sudo ln -s /etc/nginx/sites-available/mrp.test.conf /etc/nginx/sites-enabled/
  - sudo ls /etc/nginx/sites-enabled/
  - sudo ls /etc/nginx/sites-available/
  - sudo cat /etc/nginx/sites-enabled/mrp.test.conf

install:
  # - composer global require hirak/prestissimo
  - composer install

script:
  - sudo chmod -R 755 *
  - sudo nginx -c /etc/nginx/nginx.conf
  - sudo chmod -R 777 $TRAVIS_BUILD_DIR
  - sudo chown -R www-data:www-data $TRAVIS_BUILD_DIR
