name: MRP-Panel dev CI

on:
  push:
    branches: [ dev ]

  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.HK1_HOST }}
        port: ${{ secrets.HK1_PORT }}
        username: ${{ secrets.HK1_UN }}
        password: ${{ secrets.HK1_PW }}
        script: cd /www/wwwroot/MRP-Panel && git pull origin dev && composer install
